name: Pylint

on: [push]

jobs:
  test39:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --disable=global-statement,invalid-name,line-too-long,missing-function-docstring,missing-module-docstring,multiple-statements,no-else-continue,no-else-return,too-many-arguments,too-many-branches,too-many-locals,too-many-statements,use-list-literal,fixme,consider-using-f-string,comparison-with-callable zpool-iostat-viz
  test35:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --disable=global-statement,invalid-name,line-too-long,missing-function-docstring,missing-module-docstring,multiple-statements,no-else-continue,no-else-return,too-many-arguments,too-many-branches,too-many-locals,too-many-statements,use-list-literal,fixme,comparison-with-callable zpool-iostat-viz
